import os
import sys
import requests


GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
OWNER = os.environ["GITHUB_OWNER"]
REPO = os.environ["GITHUB_REPO"]
PR_NUMBER = int(os.environ["PR_NUMBER"])
INCLUDE_DATABASE_SCHEMA = os.getenv("INCLUDE_DATABASE_SCHEMA", "true").lower() == "true"

MCP_AGENT_REVIEW_URL = os.getenv(
    "MCP_AGENT_REVIEW_URL",
    "http://143.198.64.132:3011/agent-review",
)

API = "https://api.github.com"

HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def post_comment(body):
    response = requests.post(
        f"{API}/repos/{OWNER}/{REPO}/issues/{PR_NUMBER}/comments",
        headers=HEADERS,
        json={"body": body},
        timeout=30,
    )

    if response.status_code >= 400:
        print("GitHub API error")
        print("Status:", response.status_code)
        print("Response:", response.text)

    response.raise_for_status()
    return response.json()


def call_mcp_agent_review():
    payload = {
        "repo_name": REPO,
        "pr_number": PR_NUMBER,
        "include_database_schema": INCLUDE_DATABASE_SCHEMA,
    }

    response = requests.post(
        MCP_AGENT_REVIEW_URL,
        json=payload,
        timeout=180,
    )

    if response.status_code >= 400:
        print("MCP agent review error")
        print("Status:", response.status_code)
        print("Response:", response.text)

    response.raise_for_status()
    result = response.json()
    if not result.get("ok") or not result.get("review_markdown"):
        print("Unexpected MCP agent review response")
        print(result)
        sys.exit(1)
    return result


def main():
    result = call_mcp_agent_review()
    review_markdown = result["review_markdown"]
    footer = (
        "\n\n---\n"
        f"Agent review generated by `{result.get('provider')}` model `{result.get('model')}`.\n"
        f"Context used: `{result.get('context_used', {})}`"
    )
    post_comment(review_markdown + footer)


if __name__ == "__main__":
    main()
