trigger:
  - main

parameters:
  - name: environment
    type: string
    default: 'prod'
    values:
      - prod
      - local

resources:
  repositories:
    - repository: ilife-items-frontend
      type: github
      name: rabinkhadkaa/ilife-items-frontend
      ref: refs/heads/main
      endpoint: github_PAT_rabinkhadkaa_ilife-items-frontend

    - repository: ilife-build
      type: github
      name: rabinkhadkaa/ilife-build
      ref: refs/heads/main
      endpoint: github_rabinkhadkaa


variables:
  dockerRegistryServiceConnection: 'acr-ilifes-docker-connection-v2'
  imageName: 'ilifes-store'
  acrName: 'ilifesregistry.azurecr.io'
  sshServiceConnection: 'ilifes-ssh-connection'
  appDirectory: '/var/www/html'
  containerName: 'ilifes_web'
  # ACR_USERNAME: '6ceb7b59-68ae-4004-a7af-350d8b476ce7'  # appId
  # ACR_PASSWORD: '6xl8Q~T5JVWjCDbPZnBGEzXUv-o_9.A-N6IZIaX1'



stages:
  - stage: Build
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: Build
        displayName: 'Build and Push'
        pool:
          name: 'Default'
        steps:
          - checkout: self

          
          - template: check-mapping.yaml@ilife-build    
            parameters:
              environment: ${{ parameters.environment }}

          - checkout: ilife-items-frontend
            path: s/ilife-items-frontend

          # - checkout: git://rabinkhadkaa/ilife-style-css@refs/heads/main
          #   path: s/ilife-style-css

          - script: |
              echo "Listing Pipeline.workspace files after checkout:"
              ls -laR $(Pipeline.Workspace)
            displayName: 'Debug: Show checked out files'


          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              cd $(Build.SourcesDirectory)/ilife-items-frontend
              npm install
              npm run build
            displayName: 'Build React Frontend'

            
          - script: |
              echo "Listing files after checkout:"
              ls -R $(Build.SourcesDirectory)
            displayName: 'Debug: Show checked out files'

          - script: |
              echo "Copying built frontend to ilifes/public/items-frontend"
              rm -rf $(Build.SourcesDirectory)/public/items-frontend
              mkdir -p $(Build.SourcesDirectory)/public/items-frontend
              cp -r $(Build.SourcesDirectory)/ilife-items-frontend/dist/* $(Build.SourcesDirectory)/ilife/public/items-frontend
            displayName: 'Copy React Build to Public Folder'

          - task: Docker@2
            displayName: 'Docker Login to ACR'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: build
              repository: $(imageName)
              dockerfile: ilife/dockerfile
              tags: latest

          - script: |
              echo "Listing files before pushing Docker image"
              ls -la $(Build.SourcesDirectory)
            displayName: "Check Source Files Before Build"

          - task: Docker@2
            displayName: 'Push Docker Image to ACR'
            inputs:
              command: push
              repository: $(imageName)
              tags: latest


  - stage: Deploy
    displayName: 'Deploy Application'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy on Remote Server'
        pool:
          name: 'Default'
        steps:
          - checkout: self

          - task: SSH@0
            displayName: 'Copy docker-compose.yml to Server'
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: 'commands'
              commands: |
                echo "Copying docker-compose.yml to $(appDirectory)"
                scp -i /root/.ssh/id_rsa $(Build.SourcesDirectory)/docker-compose.yml root@143.198.64.132:$(appDirectory)
                echo "Copying php-env.env to $(appDirectory)"
                scp -i /root/.ssh/id_rsa $(Build.SourcesDirectory)/php-env-${{ parameters.environment }}.env root@143.198.64.132:$(appDirectory)/php-env.env

          - task: SSH@0
            displayName: 'Debugging: List Files in Build Source Directory'
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: 'commands'
              commands: |
                echo "Listing files in $(appDirectory)"
                ls -la $(appDirectory)
                echo "Listing files in $(Build.SourcesDirectory)"
                ls -la $(Build.SourcesDirectory)

          - task: Docker@2
            displayName: 'Login to ACR on Remote Server'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - script: |
              echo "Waiting for the image to be available in ACR....and print env name: php-env-${{ parameters.environment }}.env"
              sleep 10
            displayName: 'Wait for Image Availability'

          - task: SSH@0
            displayName: 'Pull and Restart Docker Containers'
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: 'commands'
              commands: |
                echo "Changing to $(appDirectory)"
                cd $(appDirectory) && ls -la

                echo "### Stopping existing containers ###"
                [ "$(docker ps -q)" ] && docker-compose -f $(appDirectory)/docker-compose.yml down 2>&1 | tee docker-compose.log || echo "No running containers to stop."

                echo "### Removing old Docker images ###"
                docker images -q $(acrName)/$(imageName):latest | grep . > /dev/null && docker rmi -f $(acrName)/$(imageName):latest || echo "No old image '$(acrName)/$(imageName):latest' to remove."

                echo "### Pulling latest image ###"
                docker pull $(acrName)/$(imageName):latest

                echo "### Starting containers with docker-compose ###"
                docker-compose -f $(appDirectory)/docker-compose.yml up -d 2>&1 | tee docker-compose.log

                echo "### Verifying running containers ###"
                docker ps -a
