services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
      MYSQL_DATABASE: "ilife"
    env_file:
      - php-env.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Add this to expose MySQL
    networks:
      - app-network

  web:
    image: ilifesregistry.azurecr.io/ilifes-store:latest  # Use the fully qualified image name
    env_file:
      - php-env.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/ilifes_store/files:/var/www/html/files  # Bind mount for saving PDF files
      - sftp-data:/var/www/html/userUploads  # Persistent storage for user uploads
    depends_on:
      - db
  
    command: >
      /bin/bash -c "a2enmod ssl && a2ensite default-ssl && apache2-foreground"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network
      
  simplesamlphp:
    image: ilifesregistry.azurecr.io/simplesamlphp:latest
    container_name: simplesamlphp
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - app-network

  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - ./docker/sftp/users.conf:/etc/sftp/users.conf:ro
      - sftp-data:/var/www/html/userUploads  # Persistent storage for uploaded files
    environment:
      SFTP_USERS: "file:/etc/sftp/users.conf"
    profiles:
      - sftp  # <-- Only starts when `--profile sftp` is specified
    networks:
      - app-network

volumes:
  db_data:
  ssl_certs:
  sftp-data:

networks:
  app-network:
    driver: bridge