version: "3.9"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
      MYSQL_DATABASE: "ilife"
    env_file:
      - php-env.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  php-fpm:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html                     # Application code
      - /mnt/ilifes_store/files:/var/www/html/files  # Host bind for PDFs/files
      - sftp-data:/var/www/html/userUploads    # Persistent storage for user uploads
    networks:
      - app-network

  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html                     # Application code
      - /mnt/ilifes_store/files:/var/www/html/files  # Optional: for serving PDFs
      - ./apache-config.conf:/usr/local/apache2/conf/httpd.conf
      - ./certs:/etc/apache2/ssl
    depends_on:
      - php-fpm
      - simplesamlphp
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '@Shova595Bhandari'
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  simplesamlphp:
    image: ilifesregistry.azurecr.io/simplesamlphp:latest
    container_name: simplesamlphp
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - app-network

  sftp:
    image: atmoz/sftp
    container_name: sftp
    ports:
      - "2222:22"
    volumes:
      - ./docker/sftp/users.conf:/etc/sftp/users.conf:ro
      - sftp-data:/var/www/html/userUploads
    environment:
      SFTP_USERS: "file:/etc/sftp/users.conf"
    networks:
      - app-network

volumes:
  db_data:
  sftp-data:

networks:
  app-network:
    driver: bridge
