customer1:password1:1001:100:/userUploads/customer1
customer2:password2:1002:100:userUploads/customer2
Paul:PaulPass:1003:100:userUploads/Paul
admin:AdminPass:1004:0:userUploads/admin
rabin:rabinpass:1005:0:userUploads/rabin
admin1:AdminPass1:1006:0:userUploads/admin1
megh:meghpass:1007:0:userUploads/megh