name: Detect Stale Branches

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"   # daily

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install jq & gh
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        sudo apt-get install -y git
        sudo apt-get install -y gh

    - name: Detect stale branches
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Starting branch scan..."

        DAYS=30
        THRESHOLD=$(date -d "$DAYS days ago" +%s)
        PROTECTED_BRANCHES="main develop stage uat feature"
        FILE=".github/stale-branches.json"

        BRANCHES=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin)

        printf "%s\n" "$BRANCHES" | while IFS= read -r BRANCH; do
          BRANCH="${BRANCH#origin/}"

          echo "----------------------------------"
          echo "Processing branch: $BRANCH"

          if echo "$PROTECTED_BRANCHES" | grep -wq "$BRANCH"; then
            echo "Skipping protected: $BRANCH"
            continue
          fi

          WARNED=$(jq -r --arg b "$BRANCH" 'has($b)' "$FILE")

          if [[ "$WARNED" == "true" ]]; then
            echo "$BRANCH already warned. Skipping."
            continue
          fi

          LAST_COMMIT=$(git log -1 --pretty="%ct" "origin/$BRANCH" 2>/dev/null || echo 0)

          if [ "$LAST_COMMIT" -gt "$THRESHOLD" ]; then
            echo "Branch active → skip"
            continue
          fi

          echo "Stale branch detected → will create issue"

          ENCODED_BRANCH=$(printf '%s' "$BRANCH" | jq -sRr @uri)

          CREATOR_GH_USERNAME=$(gh api "repos/${GITHUB_REPOSITORY}/commits/$ENCODED_BRANCH" --jq '.author.login')

          ISSUE_BODY="Branch **$BRANCH** has not received any commits recently and may be stale."
          ISSUE_URL=$(gh issue create \
              --repo "${GITHUB_REPOSITORY}" \
              --title "⚠ Stale Branch Warning: $BRANCH" \
              --body "$ISSUE_BODY" \
              --assignee "$CREATOR_GH_USERNAME")

          echo "Created issue: $ISSUE_URL"

          UPDATED_AT=$(date +%Y-%m-%dT%H:%M:%S)

          jq --arg br "$BRANCH" --arg detected "$UPDATED_AT" \
             '.[$br] = { "first_detected": $detected }' \
             "$FILE" > .github/stale-branches.tmp

          mv .github/stale-branches.tmp "$FILE"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$FILE"
          git commit -m "Update stale branch info for $BRANCH" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

        done
